runtime: nodejs16
handlers:
  - url: /.*
    script: auto
env_variables:
  COSMODB_URI: mongodb://c1091aba-0ee0-4-231-b9ee:kEx9JWuzV8UpWIBNmj9dYTjXztl5Qci6YqiN5s9BT4fLlajEgpstvhNefW5s639vbco3SLANFl9NACDbzRleFw==@c1091aba-0ee0-4-231-b9ee.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&maxIdleTimeMS=120000&appName=@c1091aba-0ee0-4-231-b9ee@
  HOST_CLOUDSQL: 35.243.214.55
  PORT_CLOUDSQL: 5432,
  USERNAME_CLOUDSQL: postgres
  PASSWORD_CLOUDSQL: usuarios
  DATABASE_CLOUDSQL: usuarios
  AWS_ACCESS_KEY_ID: AKIATEHRRWGCCUULPWOR
  AWS_SECRET_ACCESS_KEY: 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
  AWS_REGION: us-east-1