version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - dynamodb
      - mysql
      - cosmosdb
    environment:
      NODE_ENV: development
      PORT: 3000
      COSMOSDB_HOST: cosmosdb
      COSMOSDB_PORT: 10255
      COSMOSDB_USER: /dbs/todolist
      COSMOSDB_PASSWORD: password
    command: npm run dev

  dynamodb:
    image:  amazon/dynamodb-local
    container_name: my-dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      -  ./my-dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath . "
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=nico
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmosdb-emulator
    ports:
      - '10255:10255'
      - '10250:10250'
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 10
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: true
